spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.114/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.1.114
    port: 6379

#server:
#  context-path: /sell


wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 0f643e1d179f273933ccc77d0bbefafb
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: C:\h5.p12
  notifyUrl: http://ppg.nat300.top/sell/pay/notify

projectUrl:
  wechatMpAuthorize: http://ppg.nat300.top
  wechatOpenAuthorize: http://ppg.nat300.top
  sell: http://ppg.nat300.top


#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: G:\workspase\log
#  file: G:\workspase\log\sell.log